/** Canon metadata for import scripts (mirrors lib/bible/canon.ts) */
export const BIBLE_BOOKS = [
  { slug: 'gen', apiId: 'GEN', name: 'Genesis', chapters: 50, testament: 'OT', order: 1 },
  { slug: 'exo', apiId: 'EXO', name: 'Exodus', chapters: 40, testament: 'OT', order: 2 },
  { slug: 'lev', apiId: 'LEV', name: 'Leviticus', chapters: 27, testament: 'OT', order: 3 },
  { slug: 'num', apiId: 'NUM', name: 'Numbers', chapters: 36, testament: 'OT', order: 4 },
  { slug: 'deu', apiId: 'DEU', name: 'Deuteronomy', chapters: 34, testament: 'OT', order: 5 },
  { slug: 'jos', apiId: 'JOS', name: 'Joshua', chapters: 24, testament: 'OT', order: 6 },
  { slug: 'jdg', apiId: 'JDG', name: 'Judges', chapters: 21, testament: 'OT', order: 7 },
  { slug: 'rut', apiId: 'RUT', name: 'Ruth', chapters: 4, testament: 'OT', order: 8 },
  { slug: '1sa', apiId: '1SA', name: '1 Samuel', chapters: 31, testament: 'OT', order: 9 },
  { slug: '2sa', apiId: '2SA', name: '2 Samuel', chapters: 24, testament: 'OT', order: 10 },
  { slug: '1ki', apiId: '1KI', name: '1 Kings', chapters: 22, testament: 'OT', order: 11 },
  { slug: '2ki', apiId: '2KI', name: '2 Kings', chapters: 25, testament: 'OT', order: 12 },
  { slug: '1ch', apiId: '1CH', name: '1 Chronicles', chapters: 29, testament: 'OT', order: 13 },
  { slug: '2ch', apiId: '2CH', name: '2 Chronicles', chapters: 36, testament: 'OT', order: 14 },
  { slug: 'ezr', apiId: 'EZR', name: 'Ezra', chapters: 10, testament: 'OT', order: 15 },
  { slug: 'neh', apiId: 'NEH', name: 'Nehemiah', chapters: 13, testament: 'OT', order: 16 },
  { slug: 'est', apiId: 'EST', name: 'Esther', chapters: 10, testament: 'OT', order: 17 },
  { slug: 'job', apiId: 'JOB', name: 'Job', chapters: 42, testament: 'OT', order: 18 },
  { slug: 'psa', apiId: 'PSA', name: 'Psalms', chapters: 150, testament: 'OT', order: 19 },
  { slug: 'pro', apiId: 'PRO', name: 'Proverbs', chapters: 31, testament: 'OT', order: 20 },
  { slug: 'ecc', apiId: 'ECC', name: 'Ecclesiastes', chapters: 12, testament: 'OT', order: 21 },
  { slug: 'sng', apiId: 'SNG', name: 'Song of Solomon', chapters: 8, testament: 'OT', order: 22 },
  { slug: 'isa', apiId: 'ISA', name: 'Isaiah', chapters: 66, testament: 'OT', order: 23 },
  { slug: 'jer', apiId: 'JER', name: 'Jeremiah', chapters: 52, testament: 'OT', order: 24 },
  { slug: 'lam', apiId: 'LAM', name: 'Lamentations', chapters: 5, testament: 'OT', order: 25 },
  { slug: 'ezk', apiId: 'EZK', name: 'Ezekiel', chapters: 48, testament: 'OT', order: 26 },
  { slug: 'dan', apiId: 'DAN', name: 'Daniel', chapters: 12, testament: 'OT', order: 27 },
  { slug: 'hos', apiId: 'HOS', name: 'Hosea', chapters: 14, testament: 'OT', order: 28 },
  { slug: 'jol', apiId: 'JOL', name: 'Joel', chapters: 3, testament: 'OT', order: 29 },
  { slug: 'amo', apiId: 'AMO', name: 'Amos', chapters: 9, testament: 'OT', order: 30 },
  { slug: 'oba', apiId: 'OBA', name: 'Obadiah', chapters: 1, testament: 'OT', order: 31 },
  { slug: 'jon', apiId: 'JON', name: 'Jonah', chapters: 4, testament: 'OT', order: 32 },
  { slug: 'mic', apiId: 'MIC', name: 'Micah', chapters: 7, testament: 'OT', order: 33 },
  { slug: 'nam', apiId: 'NAM', name: 'Nahum', chapters: 3, testament: 'OT', order: 34 },
  { slug: 'hab', apiId: 'HAB', name: 'Habakkuk', chapters: 3, testament: 'OT', order: 35 },
  { slug: 'zep', apiId: 'ZEP', name: 'Zephaniah', chapters: 3, testament: 'OT', order: 36 },
  { slug: 'hag', apiId: 'HAG', name: 'Haggai', chapters: 2, testament: 'OT', order: 37 },
  { slug: 'zec', apiId: 'ZEC', name: 'Zechariah', chapters: 14, testament: 'OT', order: 38 },
  { slug: 'mal', apiId: 'MAL', name: 'Malachi', chapters: 4, testament: 'OT', order: 39 },
  { slug: 'mat', apiId: 'MAT', name: 'Matthew', chapters: 28, testament: 'NT', order: 40 },
  { slug: 'mrk', apiId: 'MRK', name: 'Mark', chapters: 16, testament: 'NT', order: 41 },
  { slug: 'luk', apiId: 'LUK', name: 'Luke', chapters: 24, testament: 'NT', order: 42 },
  { slug: 'jhn', apiId: 'JHN', name: 'John', chapters: 21, testament: 'NT', order: 43 },
  { slug: 'act', apiId: 'ACT', name: 'Acts', chapters: 28, testament: 'NT', order: 44 },
  { slug: 'rom', apiId: 'ROM', name: 'Romans', chapters: 16, testament: 'NT', order: 45 },
  { slug: '1co', apiId: '1CO', name: '1 Corinthians', chapters: 16, testament: 'NT', order: 46 },
  { slug: '2co', apiId: '2CO', name: '2 Corinthians', chapters: 13, testament: 'NT', order: 47 },
  { slug: 'gal', apiId: 'GAL', name: 'Galatians', chapters: 6, testament: 'NT', order: 48 },
  { slug: 'eph', apiId: 'EPH', name: 'Ephesians', chapters: 6, testament: 'NT', order: 49 },
  { slug: 'php', apiId: 'PHP', name: 'Philippians', chapters: 4, testament: 'NT', order: 50 },
  { slug: 'col', apiId: 'COL', name: 'Colossians', chapters: 4, testament: 'NT', order: 51 },
  { slug: '1th', apiId: '1TH', name: '1 Thessalonians', chapters: 5, testament: 'NT', order: 52 },
  { slug: '2th', apiId: '2TH', name: '2 Thessalonians', chapters: 3, testament: 'NT', order: 53 },
  { slug: '1ti', apiId: '1TI', name: '1 Timothy', chapters: 6, testament: 'NT', order: 54 },
  { slug: '2ti', apiId: '2TI', name: '2 Timothy', chapters: 4, testament: 'NT', order: 55 },
  { slug: 'tit', apiId: 'TIT', name: 'Titus', chapters: 3, testament: 'NT', order: 56 },
  { slug: 'phm', apiId: 'PHM', name: 'Philemon', chapters: 1, testament: 'NT', order: 57 },
  { slug: 'heb', apiId: 'HEB', name: 'Hebrews', chapters: 13, testament: 'NT', order: 58 },
  { slug: 'jas', apiId: 'JAS', name: 'James', chapters: 5, testament: 'NT', order: 59 },
  { slug: '1pe', apiId: '1PE', name: '1 Peter', chapters: 5, testament: 'NT', order: 60 },
  { slug: '2pe', apiId: '2PE', name: '2 Peter', chapters: 3, testament: 'NT', order: 61 },
  { slug: '1jn', apiId: '1JN', name: '1 John', chapters: 5, testament: 'NT', order: 62 },
  { slug: '2jn', apiId: '2JN', name: '2 John', chapters: 1, testament: 'NT', order: 63 },
  { slug: '3jn', apiId: '3JN', name: '3 John', chapters: 1, testament: 'NT', order: 64 },
  { slug: 'jud', apiId: 'JUD', name: 'Jude', chapters: 1, testament: 'NT', order: 65 },
  { slug: 'rev', apiId: 'REV', name: 'Revelation', chapters: 22, testament: 'NT', order: 66 },
]

export const bookByName = new Map(BIBLE_BOOKS.map((book) => [book.name, book]))
